# Use R language
language: r
  - release
  - devel
sudo: required
dist: bionic
#
env:
  - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
#
repos:
  CRAN: https://cloud.r-project.org
#

before_script:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - python3 -m pip install --upgrade pip
  - pip install tensorflow==2.0.0 tensorflow_probability==0.8.0 keras==2.3 six
  - R CMD INSTALL .

# Set one of you dependencies from github
r_github_packages: 
  - r-lib/testthat
  - r-lib/covr
  - r-lib/pkgdown
# set a Linux system dependency
apt_packages:
  - libxml2-dev
# print installation log
after_failure:
  - ./travis-tool.sh dump_logs

# after_success:
#   - Rscript -e 'library(covr); coveralls()'
