# Use R language
language: r
#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
  - bioc-devel
#
addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
      - python-virtualenv
      - python3-venv
# Set one of you dependencies from github
r_github_packages: 
  - r-lib/testthat
  - r-lib/covr
  - r-lib/pkgdown
# set a Linux system dependency
apt_packages:
  - libxml2-dev
# print installation log
